name: DIMOV GitHub Recent Activity

on:
  schedule:
    - cron: '30 * * * *'

jobs:
  Main-Job:
    runs-on: ubuntu-latest
    name: Update sagat79 repo's README with recent activity
    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Ping-Success:
    runs-on: ubuntu-latest
    needs: [Main-Job]
    steps:
      - run: curl -m 10 --retry 5 ${{ secrets.HEALTHCHECKS_DIMOV }}
  Ping-Failure:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: [Main-Job]
    steps:
      - run: curl -m 10 --retry 5 ${{ secrets.HEALTHCHECKS_DIMOV }}/fail
