name: Latest post workflow
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
  actions: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in dimov.xyz posts
        uses: gautamkrishnar/blog-post-workflow@v2
        with:
          max_post_count: 3
          comment_tag_name: "DIMOV-POST-LIST"
          feed_list: "https://www.dimov.xyz/rss"
          enable_keepalive: true